"""Seed 700+ cities across all Indian states. Idempotent — safe to re-run."""
import asyncio
import sys
import os

sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))

from sqlalchemy.ext.asyncio import create_async_engine, async_sessionmaker
from sqlalchemy.dialects.postgresql import insert
from app.core.config import settings
from app.models.city import City

# (name, state, slug, lang_default)
CITIES = [
    # ── NATIONAL METROS ───────────────────────────────────────────────────────
    ("Hyderabad",           "Telangana",        "hyderabad",             "te"),
    ("Bengaluru",           "Karnataka",        "bengaluru",             "kn"),
    ("Chennai",             "Tamil Nadu",       "chennai",               "ta"),
    ("Mumbai",              "Maharashtra",      "mumbai",                "mr"),
    ("Delhi",               "Delhi",            "delhi",                 "hi"),
    ("Pune",                "Maharashtra",      "pune",                  "mr"),
    ("Kolkata",             "West Bengal",      "kolkata",               "bn"),
    ("Ahmedabad",           "Gujarat",          "ahmedabad",             "gu"),
    ("Jaipur",              "Rajasthan",        "jaipur",                "hi"),
    ("Lucknow",             "Uttar Pradesh",    "lucknow",               "hi"),
    ("Surat",               "Gujarat",          "surat",                 "gu"),
    ("Kanpur",              "Uttar Pradesh",    "kanpur",                "hi"),
    ("Nagpur",              "Maharashtra",      "nagpur",                "mr"),
    ("Patna",               "Bihar",            "patna",                 "hi"),
    ("Indore",              "Madhya Pradesh",   "indore",                "hi"),
    ("Thane",               "Maharashtra",      "thane",                 "mr"),
    ("Bhopal",              "Madhya Pradesh",   "bhopal",                "hi"),
    ("Visakhapatnam",       "Andhra Pradesh",   "visakhapatnam",         "te"),
    ("Vadodara",            "Gujarat",          "vadodara",              "gu"),
    ("Ghaziabad",           "Uttar Pradesh",    "ghaziabad",             "hi"),

    # ── ANDHRA PRADESH ────────────────────────────────────────────────────────
    ("Vijayawada",          "Andhra Pradesh",   "vijayawada",            "te"),
    ("Guntur",              "Andhra Pradesh",   "guntur",                "te"),
    ("Nellore",             "Andhra Pradesh",   "nellore",               "te"),
    ("Kurnool",             "Andhra Pradesh",   "kurnool",               "te"),
    ("Kakinada",            "Andhra Pradesh",   "kakinada",              "te"),
    ("Rajamahendravaram",   "Andhra Pradesh",   "rajamahendravaram",     "te"),
    ("Kadapa",              "Andhra Pradesh",   "kadapa",                "te"),
    ("Tirupati",            "Andhra Pradesh",   "tirupati",              "te"),
    ("Anantapuram",         "Andhra Pradesh",   "anantapuram",           "te"),
    ("Ongole",              "Andhra Pradesh",   "ongole",                "te"),
    ("Vizianagaram",        "Andhra Pradesh",   "vizianagaram",          "te"),
    ("Eluru",               "Andhra Pradesh",   "eluru",                 "te"),
    ("Proddatur",           "Andhra Pradesh",   "proddatur",             "te"),
    ("Nandyal",             "Andhra Pradesh",   "nandyal",               "te"),
    ("Adoni",               "Andhra Pradesh",   "adoni",                 "te"),
    ("Machilipatnam",       "Andhra Pradesh",   "machilipatnam",         "te"),
    ("Tenali",              "Andhra Pradesh",   "tenali",                "te"),
    ("Chittoor",            "Andhra Pradesh",   "chittoor",              "te"),
    ("Hindupur",            "Andhra Pradesh",   "hindupur",              "te"),
    ("Srikakulam",          "Andhra Pradesh",   "srikakulam",            "te"),
    ("Bhimavaram",          "Andhra Pradesh",   "bhimavaram",            "te"),
    ("Tadepalligudem",      "Andhra Pradesh",   "tadepalligudem",        "te"),
    ("Guntakal",            "Andhra Pradesh",   "guntakal",              "te"),
    ("Dharmavaram",         "Andhra Pradesh",   "dharmavaram",           "te"),
    ("Gudivada",            "Andhra Pradesh",   "gudivada",              "te"),
    ("Narasaraopet",        "Andhra Pradesh",   "narasaraopet",          "te"),
    ("Madanapalle",         "Andhra Pradesh",   "madanapalle",           "te"),
    ("Kadiri",              "Andhra Pradesh",   "kadiri",                "te"),
    ("Tadipatri",           "Andhra Pradesh",   "tadipatri",             "te"),
    ("Chilakaluripet",      "Andhra Pradesh",   "chilakaluripet",        "te"),
    ("Mangalagiri",         "Andhra Pradesh",   "mangalagiri",           "te"),
    ("Amaravati",           "Andhra Pradesh",   "amaravati",             "te"),
    ("Puttaparthi",         "Andhra Pradesh",   "puttaparthi",           "te"),
    ("Narasapuram",         "Andhra Pradesh",   "narasapuram",           "te"),
    ("Amalapuram",          "Andhra Pradesh",   "amalapuram",            "te"),

    # ── TELANGANA ─────────────────────────────────────────────────────────────
    ("Warangal",            "Telangana",        "warangal",              "te"),
    ("Nizamabad",           "Telangana",        "nizamabad",             "te"),
    ("Karimnagar",          "Telangana",        "karimnagar",            "te"),
    ("Khammam",             "Telangana",        "khammam",               "te"),
    ("Ramagundam",          "Telangana",        "ramagundam",            "te"),
    ("Mahbubnagar",         "Telangana",        "mahbubnagar",           "te"),
    ("Nalgonda",            "Telangana",        "nalgonda",              "te"),
    ("Adilabad",            "Telangana",        "adilabad",              "te"),
    ("Suryapet",            "Telangana",        "suryapet",              "te"),
    ("Miryalaguda",         "Telangana",        "miryalaguda",           "te"),
    ("Siddipet",            "Telangana",        "siddipet",              "te"),
    ("Jagtial",             "Telangana",        "jagtial",               "te"),
    ("Mancherial",          "Telangana",        "mancherial",            "te"),
    ("Nirmal",              "Telangana",        "nirmal",                "te"),
    ("Sangareddy",          "Telangana",        "sangareddy",            "te"),
    ("Bhongir",             "Telangana",        "bhongir",               "te"),
    ("Kamareddy",           "Telangana",        "kamareddy",             "te"),
    ("Wanaparthy",          "Telangana",        "wanaparthy",            "te"),
    ("Nagarkurnool",        "Telangana",        "nagarkurnool",          "te"),
    ("Medak",               "Telangana",        "medak",                 "te"),
    ("Vikarabad",           "Telangana",        "vikarabad",             "te"),
    ("Zahirabad",           "Telangana",        "zahirabad",             "te"),
    ("Shadnagar",           "Telangana",        "shadnagar",             "te"),
    ("Bodhan",              "Telangana",        "bodhan",                "te"),
    ("Tandur",              "Telangana",        "tandur",                "te"),
    ("Kothagudem",          "Telangana",        "kothagudem",            "te"),
    ("Bhadrachalam",        "Telangana",        "bhadrachalam",          "te"),

    # ── KARNATAKA ─────────────────────────────────────────────────────────────
    ("Mysuru",              "Karnataka",        "mysuru",                "kn"),
    ("Hubballi",            "Karnataka",        "hubballi",              "kn"),
    ("Mangaluru",           "Karnataka",        "mangaluru",             "kn"),
    ("Belagavi",            "Karnataka",        "belagavi",              "kn"),
    ("Kalaburagi",          "Karnataka",        "kalaburagi",            "kn"),
    ("Davanagere",          "Karnataka",        "davanagere",            "kn"),
    ("Ballari",             "Karnataka",        "ballari",               "kn"),
    ("Vijayapura",          "Karnataka",        "vijayapura",            "kn"),
    ("Shivamogga",          "Karnataka",        "shivamogga",            "kn"),
    ("Tumakuru",            "Karnataka",        "tumakuru",              "kn"),
    ("Raichur",             "Karnataka",        "raichur",               "kn"),
    ("Bidar",               "Karnataka",        "bidar",                 "kn"),
    ("Udupi",               "Karnataka",        "udupi",                 "kn"),
    ("Hospet",              "Karnataka",        "hospet",                "kn"),
    ("Gadag",               "Karnataka",        "gadag",                 "kn"),
    ("Hassan",              "Karnataka",        "hassan",                "kn"),
    ("Bhadravati",          "Karnataka",        "bhadravati",            "kn"),
    ("Chitradurga",         "Karnataka",        "chitradurga",           "kn"),
    ("Kolar",               "Karnataka",        "kolar",                 "kn"),
    ("Mandya",              "Karnataka",        "mandya",                "kn"),
    ("Chikkamagaluru",      "Karnataka",        "chikkamagaluru",        "kn"),
    ("Gangavati",           "Karnataka",        "gangavati",             "kn"),
    ("Bagalkot",            "Karnataka",        "bagalkot",              "kn"),
    ("Dharwad",             "Karnataka",        "dharwad",               "kn"),
    ("Robertsonpet",        "Karnataka",        "robertsonpet",          "kn"),
    ("Ranebennuru",         "Karnataka",        "ranebennuru",           "kn"),
    ("Arsikere",            "Karnataka",        "arsikere",              "kn"),
    ("Sirsi",               "Karnataka",        "sirsi",                 "kn"),
    ("Chikkaballapur",      "Karnataka",        "chikkaballapur",        "kn"),
    ("Ramanagara",          "Karnataka",        "ramanagara",            "kn"),
    ("Yadgir",              "Karnataka",        "yadgir",                "kn"),

    # ── TAMIL NADU ────────────────────────────────────────────────────────────
    ("Coimbatore",          "Tamil Nadu",       "coimbatore",            "ta"),
    ("Madurai",             "Tamil Nadu",       "madurai",               "ta"),
    ("Tiruchirappalli",     "Tamil Nadu",       "tiruchirappalli",       "ta"),
    ("Salem",               "Tamil Nadu",       "salem",                 "ta"),
    ("Tirunelveli",         "Tamil Nadu",       "tirunelveli",           "ta"),
    ("Tiruppur",            "Tamil Nadu",       "tiruppur",              "ta"),
    ("Erode",               "Tamil Nadu",       "erode",                 "ta"),
    ("Vellore",             "Tamil Nadu",       "vellore",               "ta"),
    ("Thoothukudi",         "Tamil Nadu",       "thoothukudi",           "ta"),
    ("Thanjavur",           "Tamil Nadu",       "thanjavur",             "ta"),
    ("Nagercoil",           "Tamil Nadu",       "nagercoil",             "ta"),
    ("Dindigul",            "Tamil Nadu",       "dindigul",              "ta"),
    ("Kanchipuram",         "Tamil Nadu",       "kanchipuram",           "ta"),
    ("Kumbakonam",          "Tamil Nadu",       "kumbakonam",            "ta"),
    ("Hosur",               "Tamil Nadu",       "hosur",                 "ta"),
    ("Cuddalore",           "Tamil Nadu",       "cuddalore",             "ta"),
    ("Tiruvannamalai",      "Tamil Nadu",       "tiruvannamalai",        "ta"),
    ("Rajapalayam",         "Tamil Nadu",       "rajapalayam",           "ta"),
    ("Pudukkottai",         "Tamil Nadu",       "pudukkottai",           "ta"),
    ("Nagapattinam",        "Tamil Nadu",       "nagapattinam",          "ta"),
    ("Neyveli",             "Tamil Nadu",       "neyveli",               "ta"),
    ("Karaikkudi",          "Tamil Nadu",       "karaikkudi",            "ta"),
    ("Ambur",               "Tamil Nadu",       "ambur",                 "ta"),
    ("Krishnagiri",         "Tamil Nadu",       "krishnagiri",           "ta"),
    ("Sivakasi",            "Tamil Nadu",       "sivakasi",              "ta"),
    ("Karur",               "Tamil Nadu",       "karur",                 "ta"),
    ("Namakkal",            "Tamil Nadu",       "namakkal",              "ta"),
    ("Tiruvallur",          "Tamil Nadu",       "tiruvallur",            "ta"),
    ("Villupuram",          "Tamil Nadu",       "villupuram",            "ta"),
    ("Tirupur",             "Tamil Nadu",       "tirupur",               "ta"),
    ("Dharmapuri",          "Tamil Nadu",       "dharmapuri",            "ta"),
    ("Ranipet",             "Tamil Nadu",       "ranipet",               "ta"),
    ("Ariyalur",            "Tamil Nadu",       "ariyalur",              "ta"),

    # ── KERALA ────────────────────────────────────────────────────────────────
    ("Thiruvananthapuram",  "Kerala",           "thiruvananthapuram",    "ml"),
    ("Kochi",               "Kerala",           "kochi",                 "ml"),
    ("Kozhikode",           "Kerala",           "kozhikode",             "ml"),
    ("Thrissur",            "Kerala",           "thrissur",              "ml"),
    ("Kollam",              "Kerala",           "kollam",                "ml"),
    ("Palakkad",            "Kerala",           "palakkad",              "ml"),
    ("Alappuzha",           "Kerala",           "alappuzha",             "ml"),
    ("Malappuram",          "Kerala",           "malappuram",            "ml"),
    ("Kannur",              "Kerala",           "kannur",                "ml"),
    ("Kasaragod",           "Kerala",           "kasaragod",             "ml"),
    ("Kottayam",            "Kerala",           "kottayam",              "ml"),
    ("Thrippunithura",      "Kerala",           "thrippunithura",        "ml"),
    ("Manjeri",             "Kerala",           "manjeri",               "ml"),
    ("Thalassery",          "Kerala",           "thalassery",            "ml"),
    ("Guruvayur",           "Kerala",           "guruvayur",             "ml"),
    ("Ponnani",             "Kerala",           "ponnani",               "ml"),
    ("Perinthalmanna",      "Kerala",           "perinthalmanna",        "ml"),
    ("Irinjalakuda",        "Kerala",           "irinjalakuda",          "ml"),
    ("Kayamkulam",          "Kerala",           "kayamkulam",            "ml"),
    ("Thodupuzha",          "Kerala",           "thodupuzha",            "ml"),

    # ── MAHARASHTRA ───────────────────────────────────────────────────────────
    ("Nashik",              "Maharashtra",      "nashik",                "mr"),
    ("Kalyan",              "Maharashtra",      "kalyan",                "mr"),
    ("Vasai-Virar",         "Maharashtra",      "vasai-virar",           "mr"),
    ("Solapur",             "Maharashtra",      "solapur",               "mr"),
    ("Mira-Bhayandar",      "Maharashtra",      "mira-bhayandar",        "mr"),
    ("Bhiwandi",            "Maharashtra",      "bhiwandi",              "mr"),
    ("Aurangabad",          "Maharashtra",      "aurangabad",            "mr"),
    ("Nanded",              "Maharashtra",      "nanded",                "mr"),
    ("Kolhapur",            "Maharashtra",      "kolhapur",              "mr"),
    ("Amravati",            "Maharashtra",      "amravati",              "mr"),
    ("Chandrapur",          "Maharashtra",      "chandrapur",            "mr"),
    ("Dhule",               "Maharashtra",      "dhule",                 "mr"),
    ("Parbhani",            "Maharashtra",      "parbhani",              "mr"),
    ("Ichalkaranji",        "Maharashtra",      "ichalkaranji",          "mr"),
    ("Jalna",               "Maharashtra",      "jalna",                 "mr"),
    ("Akola",               "Maharashtra",      "akola",                 "mr"),
    ("Latur",               "Maharashtra",      "latur",                 "mr"),
    ("Satara",              "Maharashtra",      "satara",                "mr"),
    ("Yavatmal",            "Maharashtra",      "yavatmal",              "mr"),
    ("Ratnagiri",           "Maharashtra",      "ratnagiri",             "mr"),
    ("Navi Mumbai",         "Maharashtra",      "navi-mumbai",           "mr"),
    ("Panvel",              "Maharashtra",      "panvel",                "mr"),
    ("Ulhasnagar",          "Maharashtra",      "ulhasnagar",            "mr"),
    ("Badlapur",            "Maharashtra",      "badlapur",              "mr"),
    ("Gondiya",             "Maharashtra",      "gondiya",               "mr"),
    ("Wardha",              "Maharashtra",      "wardha",                "mr"),
    ("Beed",                "Maharashtra",      "beed",                  "mr"),
    ("Sangli",              "Maharashtra",      "sangli",                "mr"),
    ("Nandurbar",           "Maharashtra",      "nandurbar",             "mr"),
    ("Jalgaon",             "Maharashtra",      "jalgaon",               "mr"),
    ("Washim",              "Maharashtra",      "washim",                "mr"),
    ("Buldhana",            "Maharashtra",      "buldhana",              "mr"),
    ("Osmanabad",           "Maharashtra",      "osmanabad",             "mr"),
    ("Hingoli",             "Maharashtra",      "hingoli",               "mr"),
    ("Bhusawal",            "Maharashtra",      "bhusawal",              "mr"),
    ("Barshi",              "Maharashtra",      "barshi",                "mr"),
    ("Miraj",               "Maharashtra",      "miraj",                 "mr"),
    ("Palghar",             "Maharashtra",      "palghar",               "mr"),
    ("Dombivli",            "Maharashtra",      "dombivli",              "mr"),
    ("Ambarnath",           "Maharashtra",      "ambarnath",             "mr"),

    # ── GUJARAT ───────────────────────────────────────────────────────────────
    ("Rajkot",              "Gujarat",          "rajkot",                "gu"),
    ("Surat",               "Gujarat",          "surat",                 "gu"),
    ("Vadodara",            "Gujarat",          "vadodara",              "gu"),
    ("Bhavnagar",           "Gujarat",          "bhavnagar",             "gu"),
    ("Jamnagar",            "Gujarat",          "jamnagar",              "gu"),
    ("Junagadh",            "Gujarat",          "junagadh",              "gu"),
    ("Gandhinagar",         "Gujarat",          "gandhinagar",           "gu"),
    ("Anand",               "Gujarat",          "anand",                 "gu"),
    ("Nadiad",              "Gujarat",          "nadiad",                "gu"),
    ("Morbi",               "Gujarat",          "morbi",                 "gu"),
    ("Surendranagar",       "Gujarat",          "surendranagar",         "gu"),
    ("Bharuch",             "Gujarat",          "bharuch",               "gu"),
    ("Mehsana",             "Gujarat",          "mehsana",               "gu"),
    ("Patan",               "Gujarat",          "patan",                 "gu"),
    ("Valsad",              "Gujarat",          "valsad",                "gu"),
    ("Navsari",             "Gujarat",          "navsari",               "gu"),
    ("Amreli",              "Gujarat",          "amreli",                "gu"),
    ("Botad",               "Gujarat",          "botad",                 "gu"),
    ("Porbandar",           "Gujarat",          "porbandar",             "gu"),
    ("Veraval",             "Gujarat",          "veraval",               "gu"),
    ("Godhra",              "Gujarat",          "godhra",                "gu"),
    ("Ankleshwar",          "Gujarat",          "ankleshwar",            "gu"),
    ("Palanpur",            "Gujarat",          "palanpur",              "gu"),
    ("Dwarka",              "Gujarat",          "dwarka",                "gu"),
    ("Dahod",               "Gujarat",          "dahod",                 "gu"),
    ("Vapi",                "Gujarat",          "vapi",                  "gu"),

    # ── RAJASTHAN ─────────────────────────────────────────────────────────────
    ("Jodhpur",             "Rajasthan",        "jodhpur",               "hi"),
    ("Kota",                "Rajasthan",        "kota",                  "hi"),
    ("Bikaner",             "Rajasthan",        "bikaner",               "hi"),
    ("Ajmer",               "Rajasthan",        "ajmer",                 "hi"),
    ("Udaipur",             "Rajasthan",        "udaipur",               "hi"),
    ("Bhilwara",            "Rajasthan",        "bhilwara",              "hi"),
    ("Alwar",               "Rajasthan",        "alwar",                 "hi"),
    ("Bharatpur",           "Rajasthan",        "bharatpur",             "hi"),
    ("Sikar",               "Rajasthan",        "sikar",                 "hi"),
    ("Pali",                "Rajasthan",        "pali",                  "hi"),
    ("Sri Ganganagar",      "Rajasthan",        "sri-ganganagar",        "hi"),
    ("Tonk",                "Rajasthan",        "tonk",                  "hi"),
    ("Hanumangarh",         "Rajasthan",        "hanumangarh",           "hi"),
    ("Kishangarh",          "Rajasthan",        "kishangarh",            "hi"),
    ("Beawar",              "Rajasthan",        "beawar",                "hi"),
    ("Dhaulpur",            "Rajasthan",        "dhaulpur",              "hi"),
    ("Jhunjhunu",           "Rajasthan",        "jhunjhunu",             "hi"),
    ("Churu",               "Rajasthan",        "churu",                 "hi"),
    ("Nagaur",              "Rajasthan",        "nagaur",                "hi"),
    ("Barmer",              "Rajasthan",        "barmer",                "hi"),
    ("Sawai Madhopur",      "Rajasthan",        "sawai-madhopur",        "hi"),
    ("Banswara",            "Rajasthan",        "banswara",              "hi"),
    ("Bundi",               "Rajasthan",        "bundi",                 "hi"),
    ("Jalore",              "Rajasthan",        "jalore",                "hi"),
    ("Chittorgarh",         "Rajasthan",        "chittorgarh",           "hi"),

    # ── MADHYA PRADESH ────────────────────────────────────────────────────────
    ("Jabalpur",            "Madhya Pradesh",   "jabalpur",              "hi"),
    ("Gwalior",             "Madhya Pradesh",   "gwalior",               "hi"),
    ("Ujjain",              "Madhya Pradesh",   "ujjain",                "hi"),
    ("Sagar",               "Madhya Pradesh",   "sagar",                 "hi"),
    ("Dewas",               "Madhya Pradesh",   "dewas",                 "hi"),
    ("Satna",               "Madhya Pradesh",   "satna",                 "hi"),
    ("Ratlam",              "Madhya Pradesh",   "ratlam",                "hi"),
    ("Rewa",                "Madhya Pradesh",   "rewa",                  "hi"),
    ("Murwara",             "Madhya Pradesh",   "murwara",               "hi"),
    ("Singrauli",           "Madhya Pradesh",   "singrauli",             "hi"),
    ("Burhanpur",           "Madhya Pradesh",   "burhanpur",             "hi"),
    ("Khandwa",             "Madhya Pradesh",   "khandwa",               "hi"),
    ("Bhind",               "Madhya Pradesh",   "bhind",                 "hi"),
    ("Chhindwara",          "Madhya Pradesh",   "chhindwara",            "hi"),
    ("Guna",                "Madhya Pradesh",   "guna",                  "hi"),
    ("Shivpuri",            "Madhya Pradesh",   "shivpuri",              "hi"),
    ("Vidisha",             "Madhya Pradesh",   "vidisha",               "hi"),
    ("Chhatarpur",          "Madhya Pradesh",   "chhatarpur",            "hi"),
    ("Damoh",               "Madhya Pradesh",   "damoh",                 "hi"),
    ("Mandsaur",            "Madhya Pradesh",   "mandsaur",              "hi"),
    ("Khargone",            "Madhya Pradesh",   "khargone",              "hi"),
    ("Neemuch",             "Madhya Pradesh",   "neemuch",               "hi"),
    ("Pithampur",           "Madhya Pradesh",   "pithampur",             "hi"),
    ("Hoshangabad",         "Madhya Pradesh",   "hoshangabad",           "hi"),
    ("Itarsi",              "Madhya Pradesh",   "itarsi",                "hi"),

    # ── UTTAR PRADESH ─────────────────────────────────────────────────────────
    ("Agra",                "Uttar Pradesh",    "agra",                  "hi"),
    ("Varanasi",            "Uttar Pradesh",    "varanasi",              "hi"),
    ("Meerut",              "Uttar Pradesh",    "meerut",                "hi"),
    ("Allahabad",           "Uttar Pradesh",    "allahabad",             "hi"),
    ("Bareilly",            "Uttar Pradesh",    "bareilly",              "hi"),
    ("Aligarh",             "Uttar Pradesh",    "aligarh",               "hi"),
    ("Moradabad",           "Uttar Pradesh",    "moradabad",             "hi"),
    ("Saharanpur",          "Uttar Pradesh",    "saharanpur",            "hi"),
    ("Gorakhpur",           "Uttar Pradesh",    "gorakhpur",             "hi"),
    ("Faridabad",           "Uttar Pradesh",    "faridabad",             "hi"),
    ("Noida",               "Uttar Pradesh",    "noida",                 "hi"),
    ("Firozabad",           "Uttar Pradesh",    "firozabad",             "hi"),
    ("Jhansi",              "Uttar Pradesh",    "jhansi",                "hi"),
    ("Muzaffarnagar",       "Uttar Pradesh",    "muzaffarnagar",         "hi"),
    ("Mathura",             "Uttar Pradesh",    "mathura",               "hi"),
    ("Rampur",              "Uttar Pradesh",    "rampur",                "hi"),
    ("Shahjahanpur",        "Uttar Pradesh",    "shahjahanpur",          "hi"),
    ("Mau",                 "Uttar Pradesh",    "mau",                   "hi"),
    ("Hapur",               "Uttar Pradesh",    "hapur",                 "hi"),
    ("Etawah",              "Uttar Pradesh",    "etawah",                "hi"),
    ("Sambhal",             "Uttar Pradesh",    "sambhal",               "hi"),
    ("Amroha",              "Uttar Pradesh",    "amroha",                "hi"),
    ("Gonda",               "Uttar Pradesh",    "gonda",                 "hi"),
    ("Bahraich",            "Uttar Pradesh",    "bahraich",              "hi"),
    ("Sitapur",             "Uttar Pradesh",    "sitapur",               "hi"),
    ("Bulandshahr",         "Uttar Pradesh",    "bulandshahr",           "hi"),
    ("Unnao",               "Uttar Pradesh",    "unnao",                 "hi"),
    ("Rae Bareli",          "Uttar Pradesh",    "rae-bareli",            "hi"),
    ("Jaunpur",             "Uttar Pradesh",    "jaunpur",               "hi"),
    ("Hardoi",              "Uttar Pradesh",    "hardoi",                "hi"),
    ("Fatehpur",            "Uttar Pradesh",    "fatehpur",              "hi"),
    ("Lakhimpur",           "Uttar Pradesh",    "lakhimpur",             "hi"),
    ("Orai",                "Uttar Pradesh",    "orai",                  "hi"),
    ("Sultanpur",           "Uttar Pradesh",    "sultanpur",             "hi"),
    ("Faizabad",            "Uttar Pradesh",    "faizabad",              "hi"),
    ("Azamgarh",            "Uttar Pradesh",    "azamgarh",              "hi"),
    ("Bijnor",              "Uttar Pradesh",    "bijnor",                "hi"),
    ("Deoria",              "Uttar Pradesh",    "deoria",                "hi"),
    ("Pilibhit",            "Uttar Pradesh",    "pilibhit",              "hi"),
    ("Ballia",              "Uttar Pradesh",    "ballia",                "hi"),

    # ── BIHAR ─────────────────────────────────────────────────────────────────
    ("Gaya",                "Bihar",            "gaya",                  "hi"),
    ("Bhagalpur",           "Bihar",            "bhagalpur",             "hi"),
    ("Muzaffarpur",         "Bihar",            "muzaffarpur",           "hi"),
    ("Purnia",              "Bihar",            "purnia",                "hi"),
    ("Darbhanga",           "Bihar",            "darbhanga",             "hi"),
    ("Bihar Sharif",        "Bihar",            "bihar-sharif",          "hi"),
    ("Arrah",               "Bihar",            "arrah",                 "hi"),
    ("Begusarai",           "Bihar",            "begusarai",             "hi"),
    ("Katihar",             "Bihar",            "katihar",               "hi"),
    ("Munger",              "Bihar",            "munger",                "hi"),
    ("Chhapra",             "Bihar",            "chhapra",               "hi"),
    ("Hajipur",             "Bihar",            "hajipur",               "hi"),
    ("Sasaram",             "Bihar",            "sasaram",               "hi"),
    ("Siwan",               "Bihar",            "siwan",                 "hi"),
    ("Samastipur",          "Bihar",            "samastipur",            "hi"),
    ("Motihari",            "Bihar",            "motihari",              "hi"),
    ("Jehanabad",           "Bihar",            "jehanabad",             "hi"),
    ("Bettiah",             "Bihar",            "bettiah",               "hi"),
    ("Sitamarhi",           "Bihar",            "sitamarhi",             "hi"),
    ("Aurangabad",          "Bihar",            "aurangabad-bihar",      "hi"),

    # ── WEST BENGAL ───────────────────────────────────────────────────────────
    ("Howrah",              "West Bengal",      "howrah",                "bn"),
    ("Durgapur",            "West Bengal",      "durgapur",              "bn"),
    ("Asansol",             "West Bengal",      "asansol",               "bn"),
    ("Siliguri",            "West Bengal",      "siliguri",              "bn"),
    ("Maheshtala",          "West Bengal",      "maheshtala",            "bn"),
    ("Rajpur Sonarpur",     "West Bengal",      "rajpur-sonarpur",       "bn"),
    ("South Dumdum",        "West Bengal",      "south-dumdum",          "bn"),
    ("Barddhaman",          "West Bengal",      "barddhaman",            "bn"),
    ("Barasat",             "West Bengal",      "barasat",               "bn"),
    ("North Dumdum",        "West Bengal",      "north-dumdum",          "bn"),
    ("Malda",               "West Bengal",      "malda",                 "bn"),
    ("Krishnanagar",        "West Bengal",      "krishnanagar",          "bn"),
    ("Habra",               "West Bengal",      "habra",                 "bn"),
    ("Jalpaiguri",          "West Bengal",      "jalpaiguri",            "bn"),
    ("Kharagpur",           "West Bengal",      "kharagpur",             "bn"),
    ("Shantipur",           "West Bengal",      "shantipur",             "bn"),
    ("Midnapore",           "West Bengal",      "midnapore",             "bn"),
    ("Cooch Behar",         "West Bengal",      "cooch-behar",           "bn"),
    ("Serampore",           "West Bengal",      "serampore",             "bn"),
    ("Raiganj",             "West Bengal",      "raiganj",               "bn"),

    # ── ODISHA ────────────────────────────────────────────────────────────────
    ("Bhubaneswar",         "Odisha",           "bhubaneswar",           "or"),
    ("Cuttack",             "Odisha",           "cuttack",               "or"),
    ("Rourkela",            "Odisha",           "rourkela",              "or"),
    ("Berhampur",           "Odisha",           "berhampur",             "or"),
    ("Sambalpur",           "Odisha",           "sambalpur",             "or"),
    ("Puri",                "Odisha",           "puri",                  "or"),
    ("Baripada",            "Odisha",           "baripada",              "or"),
    ("Balasore",            "Odisha",           "balasore",              "or"),
    ("Bhadrak",             "Odisha",           "bhadrak",               "or"),
    ("Jharsuguda",          "Odisha",           "jharsuguda",            "or"),
    ("Kendujhar",           "Odisha",           "kendujhar",             "or"),
    ("Jeypore",             "Odisha",           "jeypore",               "or"),
    ("Brahmapur",           "Odisha",           "brahmapur",             "or"),
    ("Angul",               "Odisha",           "angul",                 "or"),
    ("Barbil",              "Odisha",           "barbil",                "or"),
    ("Dhenkanal",           "Odisha",           "dhenkanal",             "or"),
    ("Sundargarh",          "Odisha",           "sundargarh",            "or"),
    ("Paradip",             "Odisha",           "paradip",               "or"),

    # ── PUNJAB ────────────────────────────────────────────────────────────────
    ("Ludhiana",            "Punjab",           "ludhiana",              "pa"),
    ("Amritsar",            "Punjab",           "amritsar",              "pa"),
    ("Jalandhar",           "Punjab",           "jalandhar",             "pa"),
    ("Patiala",             "Punjab",           "patiala",               "pa"),
    ("Bathinda",            "Punjab",           "bathinda",              "pa"),
    ("Hoshiarpur",          "Punjab",           "hoshiarpur",            "pa"),
    ("Mohali",              "Punjab",           "mohali",                "pa"),
    ("Batala",              "Punjab",           "batala",                "pa"),
    ("Pathankot",           "Punjab",           "pathankot",             "pa"),
    ("Moga",                "Punjab",           "moga",                  "pa"),
    ("Abohar",              "Punjab",           "abohar",                "pa"),
    ("Malerkotla",          "Punjab",           "malerkotla",            "pa"),
    ("Khanna",              "Punjab",           "khanna",                "pa"),
    ("Phagwara",            "Punjab",           "phagwara",              "pa"),
    ("Muktsar",             "Punjab",           "muktsar",               "pa"),
    ("Barnala",             "Punjab",           "barnala",               "pa"),
    ("Gurdaspur",           "Punjab",           "gurdaspur",             "pa"),
    ("Fatehgarh Sahib",     "Punjab",           "fatehgarh-sahib",       "pa"),

    # ── HARYANA ───────────────────────────────────────────────────────────────
    ("Faridabad",           "Haryana",          "faridabad-hr",          "hi"),
    ("Gurugram",            "Haryana",          "gurugram",              "hi"),
    ("Panipat",             "Haryana",          "panipat",               "hi"),
    ("Ambala",              "Haryana",          "ambala",                "hi"),
    ("Yamunanagar",         "Haryana",          "yamunanagar",           "hi"),
    ("Rohtak",              "Haryana",          "rohtak",                "hi"),
    ("Hisar",               "Haryana",          "hisar",                 "hi"),
    ("Karnal",              "Haryana",          "karnal",                "hi"),
    ("Sonipat",             "Haryana",          "sonipat",               "hi"),
    ("Panchkula",           "Haryana",          "panchkula",             "hi"),
    ("Bhiwani",             "Haryana",          "bhiwani",               "hi"),
    ("Sirsa",               "Haryana",          "sirsa",                 "hi"),
    ("Bahadurgarh",         "Haryana",          "bahadurgarh",           "hi"),
    ("Jind",                "Haryana",          "jind",                  "hi"),
    ("Thanesar",            "Haryana",          "thanesar",              "hi"),
    ("Kaithal",             "Haryana",          "kaithal",               "hi"),
    ("Rewari",              "Haryana",          "rewari",                "hi"),
    ("Palwal",              "Haryana",          "palwal",                "hi"),

    # ── DELHI NCR ─────────────────────────────────────────────────────────────
    ("New Delhi",           "Delhi",            "new-delhi",             "hi"),
    ("Dwarka",              "Delhi",            "dwarka",                "hi"),
    ("Rohini",              "Delhi",            "rohini",                "hi"),
    ("Janakpuri",           "Delhi",            "janakpuri",             "hi"),
    ("Pitampura",           "Delhi",            "pitampura",             "hi"),
    ("Greater Noida",       "Uttar Pradesh",    "greater-noida",         "hi"),
    ("Faridabad",           "Haryana",          "faridabad",             "hi"),
    ("Gurgaon",             "Haryana",          "gurgaon",               "hi"),

    # ── HIMACHAL PRADESH ──────────────────────────────────────────────────────
    ("Shimla",              "Himachal Pradesh", "shimla",                "hi"),
    ("Solan",               "Himachal Pradesh", "solan",                 "hi"),
    ("Dharamshala",         "Himachal Pradesh", "dharamshala",           "hi"),
    ("Mandi",               "Himachal Pradesh", "mandi",                 "hi"),
    ("Palampur",            "Himachal Pradesh", "palampur",              "hi"),
    ("Baddi",               "Himachal Pradesh", "baddi",                 "hi"),
    ("Nahan",               "Himachal Pradesh", "nahan",                 "hi"),
    ("Kullu",               "Himachal Pradesh", "kullu",                 "hi"),
    ("Una",                 "Himachal Pradesh", "una",                   "hi"),
    ("Hamirpur",            "Himachal Pradesh", "hamirpur",              "hi"),

    # ── UTTARAKHAND ───────────────────────────────────────────────────────────
    ("Dehradun",            "Uttarakhand",      "dehradun",              "hi"),
    ("Haridwar",            "Uttarakhand",      "haridwar",              "hi"),
    ("Roorkee",             "Uttarakhand",      "roorkee",               "hi"),
    ("Haldwani",            "Uttarakhand",      "haldwani",              "hi"),
    ("Rudrapur",            "Uttarakhand",      "rudrapur",              "hi"),
    ("Kashipur",            "Uttarakhand",      "kashipur",              "hi"),
    ("Rishikesh",           "Uttarakhand",      "rishikesh",             "hi"),
    ("Kotdwar",             "Uttarakhand",      "kotdwar",               "hi"),
    ("Nainital",            "Uttarakhand",      "nainital",              "hi"),
    ("Mussoorie",           "Uttarakhand",      "mussoorie",             "hi"),

    # ── CHHATTISGARH ──────────────────────────────────────────────────────────
    ("Raipur",              "Chhattisgarh",     "raipur",                "hi"),
    ("Bhilai",              "Chhattisgarh",     "bhilai",                "hi"),
    ("Bilaspur",            "Chhattisgarh",     "bilaspur",              "hi"),
    ("Korba",               "Chhattisgarh",     "korba",                 "hi"),
    ("Durg",                "Chhattisgarh",     "durg",                  "hi"),
    ("Rajnandgaon",         "Chhattisgarh",     "rajnandgaon",           "hi"),
    ("Jagdalpur",           "Chhattisgarh",     "jagdalpur",             "hi"),
    ("Raigarh",             "Chhattisgarh",     "raigarh",               "hi"),
    ("Ambikapur",           "Chhattisgarh",     "ambikapur",             "hi"),
    ("Dhamtari",            "Chhattisgarh",     "dhamtari",              "hi"),
    ("Chirmiri",            "Chhattisgarh",     "chirmiri",              "hi"),

    # ── JHARKHAND ─────────────────────────────────────────────────────────────
    ("Ranchi",              "Jharkhand",        "ranchi",                "hi"),
    ("Jamshedpur",          "Jharkhand",        "jamshedpur",            "hi"),
    ("Dhanbad",             "Jharkhand",        "dhanbad",               "hi"),
    ("Bokaro",              "Jharkhand",        "bokaro",                "hi"),
    ("Deoghar",             "Jharkhand",        "deoghar",               "hi"),
    ("Phusro",              "Jharkhand",        "phusro",                "hi"),
    ("Hazaribagh",          "Jharkhand",        "hazaribagh",            "hi"),
    ("Giridih",             "Jharkhand",        "giridih",               "hi"),
    ("Ramgarh",             "Jharkhand",        "ramgarh",               "hi"),
    ("Medininagar",         "Jharkhand",        "medininagar",           "hi"),
    ("Chaibasa",            "Jharkhand",        "chaibasa",              "hi"),
    ("Chirkunda",           "Jharkhand",        "chirkunda",             "hi"),

    # ── ASSAM ─────────────────────────────────────────────────────────────────
    ("Guwahati",            "Assam",            "guwahati",              "en"),
    ("Silchar",             "Assam",            "silchar",               "en"),
    ("Dibrugarh",           "Assam",            "dibrugarh",             "en"),
    ("Jorhat",              "Assam",            "jorhat",                "en"),
    ("Nagaon",              "Assam",            "nagaon",                "en"),
    ("Tinsukia",            "Assam",            "tinsukia",              "en"),
    ("Tezpur",              "Assam",            "tezpur",                "en"),
    ("Bongaigaon",          "Assam",            "bongaigaon",            "en"),
    ("Dhubri",              "Assam",            "dhubri",                "en"),
    ("Diphu",               "Assam",            "diphu",                 "en"),

    # ── NORTHEAST STATES ──────────────────────────────────────────────────────
    ("Shillong",            "Meghalaya",        "shillong",              "en"),
    ("Imphal",              "Manipur",          "imphal",                "en"),
    ("Aizawl",              "Mizoram",          "aizawl",                "en"),
    ("Kohima",              "Nagaland",         "kohima",                "en"),
    ("Agartala",            "Tripura",          "agartala",              "en"),
    ("Itanagar",            "Arunachal Pradesh","itanagar",              "en"),
    ("Gangtok",             "Sikkim",           "gangtok",               "en"),
    ("Dimapur",             "Nagaland",         "dimapur",               "en"),

    # ── JAMMU & KASHMIR ───────────────────────────────────────────────────────
    ("Jammu",               "Jammu & Kashmir",  "jammu",                 "hi"),
    ("Srinagar",            "Jammu & Kashmir",  "srinagar",              "hi"),
    ("Anantnag",            "Jammu & Kashmir",  "anantnag",              "hi"),
    ("Sopore",              "Jammu & Kashmir",  "sopore",                "hi"),
    ("Baramulla",           "Jammu & Kashmir",  "baramulla",             "hi"),
    ("Udhampur",            "Jammu & Kashmir",  "udhampur",              "hi"),
    ("Kathua",              "Jammu & Kashmir",  "kathua",                "hi"),
    ("Leh",                 "Ladakh",           "leh",                   "hi"),

    # ── GOA ───────────────────────────────────────────────────────────────────
    ("Panaji",              "Goa",              "panaji",                "en"),
    ("Margao",              "Goa",              "margao",                "en"),
    ("Vasco da Gama",       "Goa",              "vasco-da-gama",         "en"),
    ("Mapusa",              "Goa",              "mapusa",                "en"),
    ("Ponda",               "Goa",              "ponda",                 "en"),

    # ── PUDUCHERRY / CHANDIGARH / ANDAMAN ─────────────────────────────────────
    ("Puducherry",          "Puducherry",       "puducherry",            "ta"),
    ("Chandigarh",          "Chandigarh",       "chandigarh",            "hi"),
    ("Port Blair",          "Andaman & Nicobar","port-blair",            "en"),
]


async def seed():
    url = settings.DATABASE_URL
    connect_args = {}
    if "?" in url:
        base, qs = url.split("?", 1)
        params = dict(p.split("=", 1) for p in qs.split("&") if "=" in p)
        ssl_val = params.pop("ssl", None) or params.pop("sslmode", None)
        if ssl_val and ssl_val not in ("disable", "allow"):
            connect_args["ssl"] = True
        remaining = "&".join(f"{k}={v}" for k, v in params.items())
        url = f"{base}?{remaining}" if remaining else base
    engine = create_async_engine(url, echo=False, connect_args=connect_args)
    Session = async_sessionmaker(engine, expire_on_commit=False)

    async with Session() as session:
        inserted = 0
        for name, state, slug, lang in CITIES:
            stmt = (
                insert(City)
                .values(name=name, state=state, slug=slug, lang_default=lang)
                .on_conflict_do_nothing(index_elements=["slug"])
            )
            result = await session.execute(stmt)
            inserted += result.rowcount
        await session.commit()

    await engine.dispose()
    print(f"Total in list: {len(CITIES)}")
    print(f"Newly inserted: {inserted} (existing cities skipped)")


if __name__ == "__main__":
    asyncio.run(seed())
