#!/usr/bin/env python3
"""
SEOAgent — Generates SEO metadata + structured data for a LocalIndia city page.

Usage:
  python agents/seo_agent.py --city "Vijayawada" --lang "te"
  python agents/seo_agent.py --city "Mumbai" --lang "mr"

Output (agents/output/{city_slug}/):
  seo_agent_{date}.json   — all metadata fields
  seo_agent_{date}.html   — ready-to-paste <head> snippet
"""

import argparse
import json
import os
import sys
from pathlib import Path

from dotenv import load_dotenv

sys.path.insert(0, str(Path(__file__).parent))
from base_agent import generate, save_output, build_system_prompt

LANG_NAMES = {
    "te": "Telugu", "hi": "Hindi", "ta": "Tamil", "kn": "Kannada",
    "mr": "Marathi", "bn": "Bengali", "gu": "Gujarati", "pa": "Punjabi",
    "ml": "Malayalam", "or": "Odia", "en": "English",
}

SYSTEM_PROMPT = build_system_prompt("seo_agent")


def build_user_prompt(city: str, state: str, lang: str) -> str:
    lang_name = LANG_NAMES.get(lang, lang)
    return f"""Generate complete SEO metadata for the LocalIndia city page: {city}, {state}
Regional language: {lang_name}

Return this exact JSON:
{{
  "title_tag": "...",
  "meta_description": "...",
  "og_title": "...",
  "og_description": "...",
  "h1": "...",
  "h2s": ["...", "...", "...", "..."],
  "focus_keyword": "...",
  "secondary_keywords": ["...", "..."],
  "long_tail_keywords": ["...", "...", "...", "...", "...", "...", "...", "...", "...", "..."],
  "json_ld": {{
    "@context": "https://schema.org",
    "@type": "WebPage",
    "name": "...",
    "description": "...",
    "url": "https://localsindia.com/{city.lower().replace(' ', '-')}",
    "inLanguage": ["{lang}", "en"],
    "about": {{
      "@type": "City",
      "name": "{city}",
      "containedInPlace": {{
        "@type": "State",
        "name": "{state}"
      }}
    }}
  }},
  "canonical_url": "https://localsindia.com/{city.lower().replace(' ', '-')}",
  "sitemap_priority": "0.8",
  "internal_links": [
    {{"anchor": "...", "path": "/{city.lower().replace(' ', '-')}/search?category=tiffin", "why": "..."}},
    {{"anchor": "...", "path": "/{city.lower().replace(' ', '-')}/search?category=pg-roommate", "why": "..."}},
    {{"anchor": "...", "path": "/{city.lower().replace(' ', '-')}/search?category=jobs", "why": "..."}}
  ]
}}"""


def build_html_snippet(seo: dict, city: str) -> str:
    json_ld = json.dumps(seo.get("json_ld", {}), indent=2)
    return f"""<!-- SEO metadata for {city} — generated by SEOAgent -->
<title>{seo.get('title_tag', '')}</title>
<meta name="description" content="{seo.get('meta_description', '')}">
<meta name="keywords" content="{', '.join(seo.get('long_tail_keywords', []))}">
<link rel="canonical" href="{seo.get('canonical_url', '')}">

<!-- Open Graph -->
<meta property="og:title" content="{seo.get('og_title', '')}">
<meta property="og:description" content="{seo.get('og_description', '')}">
<meta property="og:url" content="{seo.get('canonical_url', '')}">
<meta property="og:type" content="website">

<!-- Twitter Card -->
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="{seo.get('og_title', '')}">
<meta name="twitter:description" content="{seo.get('og_description', '')}">

<!-- Structured Data -->
<script type="application/ld+json">
{json_ld}
</script>"""


def run(city: str, state: str, lang: str) -> None:
    city_slug = city.lower().replace(" ", "-")
    lang_name = LANG_NAMES.get(lang, lang)
    print(f"\n[SEOAgent] {city}, {state} ({lang_name})")
    print("-" * 50)

    print(">> Generating SEO metadata with Claude...")
    raw = generate(SYSTEM_PROMPT, build_user_prompt(city, state, lang))

    # Strip markdown code fences if present
    if "```" in raw:
        raw = raw.split("```")[1]
        if raw.startswith("json"):
            raw = raw[4:]

    try:
        seo = json.loads(raw)
    except json.JSONDecodeError as e:
        print(f"[FAIL] JSON parse error: {e}")
        print(f"Raw response: {raw[:200]}")
        sys.exit(1)

    # Save JSON
    out_json = save_output("seo_agent", city_slug, json.dumps(seo, ensure_ascii=False, indent=2), "json")
    print(f"[OK] SEO data saved: {out_json}")

    # Save HTML snippet
    html = build_html_snippet(seo, city)
    out_html = save_output("seo_agent", city_slug, html, "html")
    print(f"[OK] HTML snippet saved: {out_html}")

    # Preview
    print("\n-- SEO Preview --")
    print(f"Title:    {seo.get('title_tag', '')}")
    print(f"Meta:     {seo.get('meta_description', '')}")
    print(f"H1:       {seo.get('h1', '')}")
    print(f"Focus KW: {seo.get('focus_keyword', '')}")
    kws = seo.get("long_tail_keywords", [])
    print(f"Keywords: {', '.join(kws[:5])}...")


def main():
    parser = argparse.ArgumentParser(description="SEOAgent — generate city SEO metadata")
    parser.add_argument("--city", required=True, help="City name (e.g. 'Vijayawada')")
    parser.add_argument("--state", default="Andhra Pradesh", help="State name (default: Andhra Pradesh)")
    parser.add_argument("--lang", required=True, help="Language code: te, hi, ta, etc.")
    parser.add_argument("--env-file", default=".env", help="Path to .env file")
    args = parser.parse_args()

    env_path = Path(args.env_file)
    if env_path.exists():
        load_dotenv(env_path)
    else:
        load_dotenv()

    run(args.city, args.state, args.lang)


if __name__ == "__main__":
    main()
