"""initial schema

Revision ID: 7dbd6791e1f6
Revises: 3b1c1f00ab6c
Create Date: 2026-06-09 10:00:53.237421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7dbd6791e1f6'
down_revision: Union[str, None] = '3b1c1f00ab6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
