"""add_device_tokens

Revision ID: 9c7323b7409c
Revises: d4e5f6a7b8c9
Create Date: 2026-06-11 08:17:15.123184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '9c7323b7409c'
down_revision: Union[str, None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_device_tokens_user', 'device_tokens', ['user_id'], unique=False)
    op.drop_index(op.f('idx_listing_reviews_listing'), table_name='listing_reviews')
    op.drop_index(op.f('idx_listing_reviews_user'), table_name='listing_reviews')
    op.drop_table('listing_reviews')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listing_reviews',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('listing_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name=op.f('ck_listing_reviews_rating')),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], name=op.f('listing_reviews_listing_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('listing_reviews_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('listing_reviews_pkey')),
    sa.UniqueConstraint('listing_id', 'user_id', name=op.f('uq_listing_reviews_listing_user'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_listing_reviews_user'), 'listing_reviews', ['user_id'], unique=False)
    op.create_index(op.f('idx_listing_reviews_listing'), 'listing_reviews', ['listing_id', 'created_at'], unique=False)
    op.drop_index('idx_device_tokens_user', table_name='device_tokens')
    op.drop_table('device_tokens')
    # ### end Alembic commands ###
