// Generated from the chosen CC0/public-domain photos (see public/category-covers/v/CREDITS.md).
// Business sub-type -> photo files. Edit by adding/removing photos, keep >= 2 per type where possible.
export const COVER_POOLS: Record<string, string[]> = {
  'dental': ['/category-covers/v/dental-0.jpg', '/category-covers/v/dental-1.jpg', '/category-covers/v/dental-2.jpg', '/category-covers/v/dental-3.jpg'],
  'pharmacy': ['/category-covers/v/pharmacy-0.jpg', '/category-covers/v/pharmacy-1.jpg'],
  'clinic': ['/category-covers/v/clinic-0.jpg', '/category-covers/v/clinic-1.jpg', '/category-covers/doctors.jpg'],
  'hospital': ['/category-covers/v/hospital-0.jpg', '/category-covers/v/hospital-1.jpg', '/category-covers/v/hospital-2.jpg'],
  'lab': ['/category-covers/v/lab-0.jpg', '/category-covers/v/lab-1.jpg', '/category-covers/v/lab-2.jpg'],
  'eye': ['/category-covers/v/eye-0.jpg', '/category-covers/v/eye-1.jpg', '/category-covers/v/eye-2.jpg', '/category-covers/v/eye-3.jpg'],
  'restaurant': ['/category-covers/v/restaurant-0.jpg', '/category-covers/v/restaurant-1.jpg', '/category-covers/v/restaurant-2.jpg'],
  'biryani': ['/category-covers/v/biryani-0.jpg', '/category-covers/v/biryani-1.jpg', '/category-covers/v/biryani-2.jpg', '/category-covers/v/biryani-3.jpg'],
  'southindian': ['/category-covers/v/southindian-0.jpg', '/category-covers/v/southindian-1.jpg', '/category-covers/v/southindian-2.jpg', '/category-covers/v/southindian-3.jpg', '/category-covers/v/southindian-4.jpg', '/category-covers/v/southindian-5.jpg', '/category-covers/tiffin.jpg'],
  'fastfood': ['/category-covers/v/fastfood-0.jpg', '/category-covers/v/fastfood-1.jpg', '/category-covers/v/fastfood-2.jpg', '/category-covers/v/fastfood-3.jpg'],
  'juice': ['/category-covers/v/juice-0.jpg', '/category-covers/v/juice-1.jpg', '/category-covers/v/juice-2.jpg'],
  'bakery': ['/category-covers/v/bakery-0.jpg', '/category-covers/v/bakery-1.jpg', '/category-covers/v/bakery-2.jpg', '/category-covers/v/bakery-3.jpg', '/category-covers/v/bakery-4.jpg', '/category-covers/v/bakery-5.jpg'],
  'sweets': ['/category-covers/v/sweets-0.jpg', '/category-covers/v/sweets-1.jpg', '/category-covers/v/sweets-2.jpg', '/category-covers/v/sweets-3.jpg', '/category-covers/v/sweets-4.jpg', '/category-covers/v/sweets-5.jpg', '/category-covers/v/sweets-6.jpg', '/category-covers/v/sweets-7.jpg'],
  'tea': ['/category-covers/v/tea-0.jpg'],
  'school': ['/category-covers/v/school-0.jpg', '/category-covers/v/school-1.jpg'],
  'college': ['/category-covers/v/college-0.jpg', '/category-covers/v/college-1.jpg', '/category-covers/v/college-2.jpg'],
  'coaching': ['/category-covers/v/coaching-0.jpg', '/category-covers/v/coaching-1.jpg', '/category-covers/education.jpg'],
  'kindergarten': ['/category-covers/v/kindergarten-0.jpg'],
  'hostel': ['/category-covers/v/hostel-0.jpg', '/category-covers/v/hostel-1.jpg', '/category-covers/v/hostel-2.jpg', '/category-covers/pg-roommate.jpg'],
  'salon': ['/category-covers/v/salon-0.jpg', '/category-covers/v/salon-1.jpg', '/category-covers/v/salon-2.jpg'],
  'laundry': ['/category-covers/v/laundry-0.jpg', '/category-covers/v/laundry-1.jpg'],
  'photo': ['/category-covers/v/photo-0.jpg', '/category-covers/v/photo-1.jpg'],
  'vet': ['/category-covers/v/vet-0.jpg', '/category-covers/v/vet-1.jpg', '/category-covers/v/vet-2.jpg', '/category-covers/v/vet-3.jpg', '/category-covers/v/vet-4.jpg', '/category-covers/v/vet-5.jpg'],
  'tailor': ['/category-covers/v/tailor-0.jpg', '/category-covers/v/tailor-1.jpg', '/category-covers/v/tailor-2.jpg'],
  'clothes': ['/category-covers/v/clothes-0.jpg', '/category-covers/v/clothes-1.jpg', '/category-covers/v/clothes-2.jpg', '/category-covers/v/clothes-3.jpg'],
  'textiles': ['/category-covers/v/textiles-0.jpg', '/category-covers/v/textiles-1.jpg', '/category-covers/fashion.jpg'],
  'jewellery': ['/category-covers/v/jewellery-0.jpg', '/category-covers/v/jewellery-1.jpg'],
  'footwear': ['/category-covers/v/footwear-0.jpg'],
  'bike': ['/category-covers/v/bike-0.jpg', '/category-covers/v/bike-1.jpg', '/category-covers/v/bike-2.jpg', '/category-covers/vehicles.jpg'],
  'car': ['/category-covers/v/car-0.jpg'],
  'garage': ['/category-covers/v/garage-0.jpg', '/category-covers/v/garage-1.jpg', '/category-covers/v/garage-2.jpg', '/category-covers/v/garage-3.jpg'],
  'mobile': ['/category-covers/v/mobile-0.jpg', '/category-covers/electronics.jpg'],
  'computer': ['/category-covers/v/computer-0.jpg', '/category-covers/v/computer-1.jpg', '/category-covers/v/computer-2.jpg'],
  'appliance': ['/category-covers/v/appliance-0.jpg', '/category-covers/v/appliance-1.jpg'],
  'events': ['/category-covers/v/events-0.jpg', '/category-covers/v/events-1.jpg', '/category-covers/v/events-2.jpg', '/category-covers/v/events-3.jpg', '/category-covers/events.jpg'],
  'supermarket': ['/category-covers/v/supermarket-0.jpg', '/category-covers/v/supermarket-1.jpg', '/category-covers/v/supermarket-2.jpg'],
  'grocery': ['/category-covers/v/grocery-0.jpg', '/category-covers/v/grocery-1.jpg', '/category-covers/businesses.jpg'],
  'hardware': ['/category-covers/v/hardware-0.jpg', '/category-covers/v/hardware-1.jpg'],
  'stationery': ['/category-covers/v/stationery-0.jpg', '/category-covers/v/stationery-1.jpg'],
  'general': ['/category-covers/v/general-0.jpg', '/category-covers/v/general-1.jpg', '/category-covers/services.jpg', '/category-covers/classifieds.jpg'],
  'realestate': ['/category-covers/v/realestate-0.jpg', '/category-covers/v/realestate-1.jpg', '/category-covers/v/realestate-2.jpg', '/category-covers/v/realestate-3.jpg', '/category-covers/real-estate.jpg'],
  'furniture': ['/category-covers/v/furniture-0.jpg', '/category-covers/v/furniture-1.jpg', '/category-covers/v/furniture-2.jpg', '/category-covers/v/furniture-3.jpg', '/category-covers/v/furniture-4.jpg', '/category-covers/furniture.jpg'],
  'office': ['/category-covers/v/office-0.jpg', '/category-covers/v/office-1.jpg', '/category-covers/jobs.jpg'],
};
